# -*- coding: utf-8 -*-
"""sumosoft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4o9aSgTmnwZDdp_5mv22oIhBSgLcU4z
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

train_df=pd.read_csv("/content/train_u6lujuX_CVtuZ9i.csv")
test_df= pd.read_csv("/content/test_Y3wMUE5_7gLdaTN.csv")

train_df.info()

test_df.info()

train_df.isnull().sum()

test_df.isnull().sum()

"""Both Dataset Were loaded to understand datatype, missing values."""

loan_median= train_df.groupby("Property_Area")["LoanAmount"].median()

loan_median

train_df['LoanAmount'] = train_df['LoanAmount'].fillna(train_df.groupby('Property_Area')['LoanAmount'].transform('median'))

train_df['LoanAmount']



test_df['LoanAmount'] = test_df['LoanAmount'].fillna(
    test_df.groupby('Property_Area')['LoanAmount'].transform('median')
)

test_df['LoanAmount']



"""IQR Iin Income"""

Q1 = train_df['ApplicantIncome'].quantile(0.25)
Q3 = train_df['ApplicantIncome'].quantile(0.75)
IQR= Q3 - Q1

Lower_Bound = Q1-1.5 * IQR
Upper_Bound = Q3+1.5 * IQR

Lower_Bound = Q1-1.5 * IQR
Upper_Bound = Q3+1.5 * IQR

Lower_Bound

Upper_Bound

test_df = test_df[
    (test_df['ApplicantIncome'] >= Lower_Bound) &
    (test_df['ApplicantIncome'] <= Upper_Bound)
]

Q1 = test_df['ApplicantIncome'].quantile(0.25)
Q3 = test_df['ApplicantIncome'].quantile(0.75)
IQR= Q3 - Q1

Lower_Bound = Q1-1.5 * IQR
Upper_Bound = Q3+1.5 * IQR

Lower_Bound

Upper_Bound







avg_loan = (
    test_df[test_df['Credit_History'] == 1.0]
    .groupby(['Gender', 'Property_Area'])['LoanAmount']
    .mean()
    .reset_index()
)

avg_loan =(
    test_df[test_df['Credit_History']==1.0].groupby(['Gender','Property_Area'])['LoanAmount'].mean().reset_index()


           )

avg_loan

"""The average loan amount calculated by gender and property area for
applicants with a credit history of 1.0

"""

plt.figure(figsize=(8,5))
sns.boxplot(x='Education', y='ApplicantIncome', data=test_df)
plt.title('Applicant Income by Education')
plt.xlabel('Education')
plt.ylabel('Applicant Income')
plt.show()

plt.figure(figsize=(9,10))
sns.boxplot(x='Education',y='ApplicantIncome',data=test_df)
plt.title("Applicant Income By Education")
plt.xlabel("Education")
plt.ylabel("Appplicant Income")
plt.show()

"""#Insights

- Graduates usually have higher incomes than non-graduates.

- Income among graduates varies more, showing a wider range.

- Non-graduates have lower, more concentrated incomes.

- Income growth potential seems limited for non-graduates.

- High-income outliers are more common among graduates.







"""



#Correlation Heatmap For Numeric Feature



plt.figure(figsize=(10,6))
sns.heatmap(test_df.select_dtypes(include='number').corr(),
    annot=True,
    cmap='coolwarm'
)
plt.title('Correlation Heatmap of Numeric Features')
plt.show()



"""#Insights

- LoanAmount shows a positive correlation with ApplicantIncome, indicating  higher-income applicants tend to request larger loan amounts.

- DTI is positively correlated with LoanAmount and negatively correlated with ApplicantIncome, confirming that higher loans relative to income increase repayment burden.

- Credit_History has weak correlation with most numeric variables, suggesting it acts as an independent approval factor rather than being income-driven.

- CoapplicantIncome has low to moderate correlation with LoanAmount, implying secondary income provides limited influence compared to primary income.

"""





"""Calculate Debt to income ratio(DTI)"""



test_df['DTI'] = test_df['LoanAmount'] / test_df['ApplicantIncome']

test_df['DTI']





income_median = train_df['ApplicantIncome'].median()

income_median



high_risk = test_df[
    (test_df['Property_Area'] == 'Rural') &
    (test_df['ApplicantIncome'] < income_median) &
    (test_df['DTI'] > 0.40)
]

high_risk

"""#Insights

- Applicants from rural areas with lower income levels and higher
debt-to-income ratios represent a higher credit risk. A DTI above 40%
- indicates increased repayment burden, particularly for applicants with
limited income capacity.

- Applicants from rural property areas with lower applicant income and higher loan-to-income ratios represent the high-risk segment.
-  These applicants typically show greater financial stress, especially when credit history is weak, indicating a higher likelihood of repayment challenges. -  Setting stricter approval thresholds for high debt-to-income ratios can help reduce lending risk.
"""





