# -*- coding: utf-8 -*-
"""marketing .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4Vs0TJOrL13D5N8xoGhJ9TUclYkFtJK
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv("/content/marketing campaign dataset.csv")

df.head()

df.shape

"""there are 10000 rows and 20 coloumns

"""

df.info()

"""we can see here datatype of Coloumns"""



df.describe()



#  total revenue  from campaigns

total_revenue = df["Revenue"].sum()

total_revenue

"""total Revenue ($197 million dollars)"""

# total amount spent on campaigns

Campaign_Cost=df['Campaign_Cost'].sum()

Campaign_Cost

"""total Campaign_Cost ($52 million dollars)




"""



# ROI OF the Campaign

ROI = (total_revenue - Campaign_Cost) / Campaign_Cost

ROI

"""The Return on Investment 2.79 %"""



#Revenue by Marketing Channel

revenue_channel=df.groupby("Channel")["Revenue"].sum()

revenue_channel

"""Google Ads marketing channel is most effective in generating revenue with $34 million"""



#visualize Revenue by Channel

plt.figure(figsize= (8,5))
sns.barplot(x=revenue_channel.index, y=revenue_channel.values)

plt.title("Revenue by Marketing Channel")
plt.xlabel("Marketing Channel")
plt.ylabel("total_revenue")

plt.show()

"""Insights-

  we can clearly see google ads marketing channel with $ 32million dollars
    on second place influencer channel with $ 33 million


"""



#clicks based on device type

device_type=df.groupby("Device")["Clicks"].sum()

device_type





#Visualize device Clicks

sns.barplot(x=device_type.index,y=device_type.values)

"""there are 3 devices are there desktop, Mobile ,Tablet total clicks of mobile users are on the top ,On 2nd place Tablet Are there it show mobile and tablet use are much higher compare to desktop

mobile has the highest clicks,the company should optimize mobile ads

"""

#Customer Type Revenue

customer_Type=df.groupby("Customer_Type")["Revenue"].sum()

customer_Type

"""
new customers or returning customers generate more revenue."""



# Clicks,Impression,Conversion

Total_clicks=df["Clicks"].sum()
total_Impression=df["Impressions"].sum()
total_Conversion=df["Conversions"].sum()

Total_clicks=df["Clicks"].sum()

Total_clicks

total_Impression=df["Impressions"].sum()

total_Impression

total_Conversion=df["Conversions"].sum()

total_Conversion

"""Total Impressions: 401432438(400 million)
Total Clicks: 29819293(30 million)
Total Conversions: 1993329 (2 million)
"""



# Click Rate

click_rate = Total_clicks/total_Impression

click_rate

"""the Click Rate 0.07%
CR shows how effective the ads are at attracting user attention.
"""



df["Date"] = pd.to_datetime(df["Date"])

revenue_trend = df.groupby("Date")["Revenue"].sum()

revenue_trend.plot()

plt.title("Revenue Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Revenue")

plt.show()